# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    name: Setup project and deploy on GCR
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 1
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup gcloud
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Build on GCP using Cloud Build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |-
          mv appsettings.json appsettings.json.template
          envsubst < ./appsettings.json.template > appsettings.json
          rm appsettings.json.template -f
          gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/exemplo-dotnet

      - name: Deploy on GCR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |-
          gcloud run deploy exemplo-dotnet \
            --image gcr.io/$GCP_PROJECT_ID/exemplo-dotnet \
            --project $GCP_PROJECT_ID \
            --platform managed \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --quiet
